### ISSUE TITLE
Adjust memory requirement to allow t4g.small EC2 instance type

### ISSUE THREAD

**Issue by conclusionlogic** [siderolabs/terraform-provider-talos#114]
Hello,

I tried to launch a Talos node for testing in AWS in `eu-west-2` region but it failed.
All goes well when`t3.small` EC2 instance type is used, but with `t4g.small` the threshold is exceeded.
Feels like it's slightly too strict.
Error message:
```
waiting for all nodes memory sizes: 1 error occurred:
	* node "<node_ip>" does not meet memory requirements: expected at least 1898 MiB, actual 1831 MiB
```

Would like to use t4g class instances as they tend to be cheaper and more performant.

**Comment by smira** [comment]
Decision: make list of checks configurable
