### ISSUE TITLE
Drop use of `internal` package for easier downstream Pulumi provider?

### ISSUE THREAD

**Issue by ringods** [siderolabs/terraform-provider-talos#130]
Hello @frezbo,

At [Pulumiverse](https://github.com/pulumiverse), we recently took over the Pulumi provider from you. We have an easy way to bridge the TF provider and expose everything as Pulumi resources.

There is annoyance in the setup of the TF provider using your Go code because you have it in `internal/talos`. The `internal` part makes a lot of the code private. In the Pulumi provider, we have to create a `shim` to access some of the TF code in our Pulumi provider.

https://github.com/pulumiverse/pulumi-talos/tree/main/provider/shim

Would you be open to drop the use of the `internal` package, so we can simplify the setup in our downstream Pulumi provider too?

**Comment by frezbo** [comment]
Yes, i can do that, this was just following a standard TF project schema, but if it makes easier to consume downstream can update it.

**Comment by ringods** [comment]
@frezbo besides this refactoring, do you have any other changes which warrants a new TF provider release? On Pulumi side, we usually take in tagged TF provider releases when bridging.

**Comment by frezbo** [comment]
> @frezbo besides this refactoring, do you have any other changes which warrants a new TF provider release? On Pulumi side, we usually take in tagged TF provider releases when bridging.

will do a new release along talos 1.6 due in Dec, otherwise only bug fixes will have an associated release
