### ISSUE TITLE
`terraform destroy` should destroy the cluster

### ISSUE THREAD

**Issue by mirceanton** [siderolabs/terraform-provider-talos#133]
I managed to set up a Talos cluster using the basic example provided, and I noticed that if I run `terraform destroy` the `talos_machine_configuration_apply` objects get destroyed but nothing really happens.

I think that running `terraform destroy`, or rather destroying the `talos_machine_configuration_apply` object, should essentially run `talosctl reset` on the node.

**Comment by smira** [comment]
Add a flag to do `talosctl reset` when `talos_machine_configuration_apply` is destroyed.
