### ISSUE TITLE
Specify installer image for the `talos_machine_configuration_apply`

### ISSUE THREAD

**Issue by mirceanton** [siderolabs/terraform-provider-talos#134]
Given that the current workflow requires users to specify a custom installer image, I think it would be better to have a dedicated field in the `talos_machine_configuration_apply` to specify an installer image, that way it can also be taken into account during upgrades, since, as far as I can tell from some minimal testing, there is no clear way to specify an installer image for upgrades so that system extensions are taken into account.

**Comment by smira** [comment]
TF provider doesn't support upgrades at the moment.

**Comment by maykopetersen** [comment]
You can set up the `config_patches` argument in `talos_machine_configuration_apply` like this:
```hcl
resource "talos_machine_configuration_apply" "example" {
...
  config_patches = [
    yamlencode({
      machine = {
        install = {
          image = "factory.talos.dev/installer/<image_id>:v1.7.4"
        }
      }
    })
  ]
}
```

Remember: custom installer image is a `key` of configuration YAML file used by Talos. So, you can use `config_patches` argument to solve it.

**Comment by perfectra1n** [comment]
Yeah, but if you already have an existing cluster and then modify the `<image_id>` to something else that has different extensions, the node is not upgraded to reflect the change in extensions @maykopetersen.
