### ISSUE TITLE
due to routing talosctl over an ssh tunnel id like to customize the talosctl port via the provider

### ISSUE THREAD

**Issue by wibed** [siderolabs/terraform-provider-talos#136]

**Comment by smira** [comment]
Should be already possible by specifying a custom endpoint as `IP:port` (or `hostname:port`).

**Comment by wibed** [comment]
just for the record. this is possible?

```tf
variable "talosclusterpanelip" { 
  type = string
  default = "10.0.48.20:50000"
}
```

**Comment by frezbo** [comment]
> just for the record. this is possible?
> 
> ```terraform
> variable "talosclusterpanelip" { 
>   type = string
>   default = "10.0.48.20:50000"
> }
> ```

yes, that should work
