### ISSUE TITLE
Remove defaults for KubePrismSupport, DiskQuotaSupport and certSAN

### ISSUE THREAD

**Issue by myoung34** [siderolabs/terraform-provider-talos#151]
Im attempting to migrate my random controlplane + worker config yaml to the terraform provider [here](https://github.com/myoung34/homelab/pull/315/files)

I was able to get a 1:1 match except:

* KubePrismSupport always has a value. it defaults to true and I cannot nil it out, so I have to set it to enabled:false, but it keeps the port attribute. The only way to remove it is to use `edit mc` to give me this change
```
-                       KubePrismSupport:               &{ServerEnabled: &false, ServerPort: 7445}, 
+                       KubePrismSupport:               nil,
```

* DiskQuotaSupport always has a value. it defaults to true and I cannot nil it out, so I have to set it to false. The only way to remove it is to use `edit mc` to give me this change
```
-                       DiskQuotaSupport:               &false,
+                       DiskQuotaSupport:               nil,
```

* certSANs always includes the VIP. While this is probably fine it gives me very little full control over the values. if i set certSANs in the `config_patches` it always includes the value of my VIP which I did not include in this apply and is not expected. This doesnt actually show up in the terraform diff even though it will be set.

**Comment by myoung34** [comment]
This happens behind the scenes. Since its not in my yaml or plan there's nothing to patch unless there's something Im missing

**Comment by smira** [comment]
You have `talos_version` to control the defaults based on Talos version you're generating the machine config for.

You should be still be able to override whatever defaults are with config patches.
