### ISSUE TITLE
Datasource talos_cluster_kubeconfig is not idempotent

### ISSUE THREAD

**Issue by FlxPeters** [siderolabs/terraform-provider-talos#155]
Given I use the example code for the `talos_cluster_kubeconfig` data source,
a new kubeconfig is a returned on every terraform apply.

```terrafom
data "talos_cluster_kubeconfig" "this" {
  depends_on = [
    talos_machine_bootstrap.this
  ]
  client_configuration = talos_machine_secrets.this.client_configuration
  node                 = "10.5.0.2"
}
```

This is not a show-stopper bug, but the data source will change on each run which is a change in the plan.

Is this an intended behavior?

**Comment by frezbo** [comment]
yes, that's the intended behavior, maybe we can improve it to generate the client kubeconfig from machine secrets instead of retrieving from the talos api which would return a new one every single time

**Comment by shkarface** [comment]
+1

**Comment by luis-guimaraes-exoawk** [comment]
@frezbo It's be great if we could make it so that it's a fixed value or at least only changes when strictly required

**Comment by frezbo** [comment]
The only fix would be to convert this to a `resource` as opposed to a `data_source` due TF provider internals
