### ISSUE TITLE
Submit the public key for Provider signing to OpenTofu

### ISSUE THREAD

**Issue by mpepping** [siderolabs/terraform-provider-talos#162]
Using the siderolabs/talos provider with OpenTofu shows a warning on Signature validation:

`Installed siderolabs/talos v0.5.0. Signature validation was skipped due to the registry not containing GPG keys for this provider`

There's a "Submit new Provider Signing Key" issue template on the OpenTofu registry project to make submitting GPG public keys easy: 

https://github.com/opentofu/registry/issues/new/choose

**Would you please take a moment to submit the public signing key to the OpenTofu project, so that tofu users can install the siderolabs/talos provider without any warnings?** 

An example of a submitted issue can be [found here](https://github.com/opentofu/registry/issues/206).

**Comment by frezbo** [comment]
Submitted here: https://github.com/opentofu/registry/issues/637
