### ISSUE TITLE
talos_cluster_health also checks destroyed VM's IP

### ISSUE THREAD

**Issue by hakobian4** [siderolabs/terraform-provider-talos#166]
### Description
I have created Kubernetes cluster with 3 nodes using Terraform: 1 control-plane and 2 worker-nodes. The `terraform apply` has been completed successfully. After that I decided to remove one of the worker-nodes and decreased the count of the worker-nodes. Then I saw this error. The problem is the `talos_cluster_health` still remembers the removed node IP address (192.168.2.246). I have checked in state file, it isn't there. Is anyone came across this issue?

### Logs
```text
data.talos_cluster_health.cluster_health["armen"]: Still reading... [4m30s elapsed]
data.talos_cluster_health.cluster_health["armen"]: Still reading... [4m40s elapsed]
data.talos_cluster_health.cluster_health["armen"]: Still reading... [4m50s elapsed]
data.talos_cluster_health.cluster_health["armen"]: Still reading... [5m0s elapsed]
╷
│ Error: health check messages:
│ discovered nodes: ["192.168.2.245" "192.168.2.244"]
│ waiting for etcd to be healthy: ...
│ waiting for etcd to be healthy: OK
│ waiting for etcd members to be consistent across nodes: ...
│ waiting for etcd members to be consistent across nodes: OK
│ waiting for etcd members to be control plane nodes: ...
│ waiting for etcd members to be control plane nodes: OK
│ waiting for apid to be ready: ...
│ waiting for apid to be ready: OK
│ waiting for all nodes memory sizes: ...
│ waiting for all nodes memory sizes: OK
│ waiting for all nodes disk sizes: ...
│ waiting for all nodes disk sizes: OK
│ waiting for kubelet to be healthy: ...
│ waiting for kubelet to be healthy: OK
│ waiting for all nodes to finish boot sequence: ...
│ waiting for all nodes to finish boot sequence: OK
│ waiting for all k8s nodes to report: ...
│ waiting for all k8s nodes to report: unexpected nodes with IPs ["192.168.2.246"]
│ 
│ 
│   with data.talos_cluster_health.cluster_health["armen"],
│   on talos.tf line 94, in data "talos_cluster_health" "cluster_health":
│   94: data "talos_cluster_health" "cluster_health" {
│ 
│ rpc error: code = DeadlineExceeded desc = context deadline exceeded

```

### Environment

- Talos version: `v1.7.1`
- Kubernetes version: `v1.30.0`
- Platform: Bare-metal

**Comment by frezbo** [comment]
Could you post the snippet of code used for `talos_cluster_health`?

**Comment by hakobian4** [comment]
data "talos_cluster_health" "cluster_health" {
  for_each = local.clusters

  client_configuration = talos_machine_secrets.talos_secrets.client_configuration
  control_plane_nodes  = [proxmox_vm_qemu.controlplane[each.key].default_ipv4_address]
  worker_nodes         = [for worker in proxmox_vm_qemu.worker : worker.default_ipv4_address]
  endpoints            = [proxmox_vm_qemu.controlplane[each.key].default_ipv4_address]
  timeouts = {
    read = "1h"
  }
}

**Comment by edikmkoyan** [comment]
@frezbo can you please reflect on this?
https://github.com/siderolabs/terraform-provider-talos/issues/166#issuecomment-2160392283

**Comment by frezbo** [comment]
could you try this version https://github.com/siderolabs/terraform-provider-talos/releases/tag/v0.6.0-alpha.0

**Comment by TomyLobo** [comment]
> could you try this version https://github.com/siderolabs/terraform-provider-talos/releases/tag/v0.6.0-alpha.0

@frezbo I'm having this same issue (albeit with slightly different messages) in 0.6.1.
So that didn't help, unfortunately :/

Here's the output from 0.6.1:
```
data.talos_cluster_health.this: Still reading... [5m0s elapsed]
[…]
╷
│ Warning: failed checks
│ 
│   with data.talos_cluster_health.this,
│   on main.tf line 231, in data "talos_cluster_health" "this":
│  231: data "talos_cluster_health" "this" {
│ 
│ waiting for etcd to be healthy: ...
│ waiting for etcd to be healthy: OK
│ waiting for etcd members to be consistent across nodes: ...
│ waiting for etcd members to be consistent across nodes: OK
│ waiting for etcd members to be control plane nodes: ...
│ waiting for etcd members to be control plane nodes: etcd member ips ["172.16.37.52" "172.16.37.55"] are not subset of control plane node ips ["172.16.37.52"]
│ 
╵
╷
│ Error: cluster health check failed
│ 
│   with data.talos_cluster_health.this,
│   on main.tf line 231, in data "talos_cluster_health" "this":
│  231: data "talos_cluster_health" "this" {
│ 
│ context deadline exceeded
╵
```

The main issue, _I think_, is that it checks cluster health during refresh at all.
But I barely started using Terraform, so maybe that's somehow necessary.
