### ISSUE TITLE
`talos_machine_configuration_apply` applying configuration to endpoint instead of `node`

### ISSUE THREAD

**Issue by NPastorale** [siderolabs/terraform-provider-talos#17]
I have performed several tests and I'm now fairly certain that the `talos_machine_configuration_apply` resource is applying its `machine_configuration` parameter to the endpoint defined in it, instead of using the list of 'nodes' parameter.

I arrived at this conclusion after successfully applying the `talos_machine_secrets`, `talos_machine_configuration_worker`, `talos_client_configuration`, `talos_machine_configuration_apply` for the control plane, `talos_machine_bootstrap` and `talos_cluster_kubeconfig`, i.e. the same config I'm pasting below.

Applying that will result in a master being bootstrapped into a functional cluster.

If I uncomment the `resource.talos_machine_configuration_apply.worker_config_apply` section and do a `terraform apply` it will apply the config, but it will do so to the `192.168.122.203` in this example, instead of the expected `192.168.122.28` from the `nodes` parameter. Which effectively will not only leave the cluster inoperable, but the `192.168.122.28` will not receive the configuration being applied.

Let me know if any further details are needed.

Thanks!

```main.tf
terraform {
  required_version = ">= 0.12"
  required_providers {
    talos = {
      source  = "siderolabs/talos"
      version = "0.1.0-alpha.3"
    }
  }
}

provider "talos" {}

resource "talos_machine_secrets" "machine_secrets" {}

resource "talos_machine_configuration_controlplane" "machineconfig_cp" {
  cluster_name     = var.cluster_name
  cluster_endpoint = var.cluster_endpoint
  docs_enabled     = false
  examples_enabled = false
  machine_secrets  = talos_machine_secrets.machine_secrets.machine_secrets
  config_patches = [
    templatefile("${path.module}/templates/patch.yaml.tmpl", {
      disk = "/dev/vda"
    })
  ]
}

resource "talos_machine_configuration_worker" "machineconfig_worker" {
  cluster_name     = var.cluster_name
  cluster_endpoint = var.cluster_endpoint
  docs_enabled     = false
  examples_enabled = false
  machine_secrets  = talos_machine_secrets.machine_secrets.machine_secrets
  config_patches = [
    templatefile("${path.module}/templates/patch.yaml.tmpl", {
      disk = "/dev/vda"
    })
  ]
}

resource "talos_client_configuration" "talosconfig" {
  cluster_name    = var.cluster_name
  machine_secrets = talos_machine_secrets.machine_secrets.machine_secrets
  endpoints       = ["192.168.122.203"]
}

resource "talos_machine_configuration_apply" "cp_config_apply" {
  talos_config          = talos_client_configuration.talosconfig.talos_config
  machine_configuration = talos_machine_configuration_controlplane.machineconfig_cp.machine_config
  mode                  = "reboot"
  nodes                 = ["192.168.122.203"]
}

# resource "talos_machine_configuration_apply" "worker_config_apply" {
#   talos_config          = talos_client_configuration.talosconfig.talos_config
#   machine_configuration = talos_machine_configuration_worker.machineconfig_worker.machine_config
#   mode                  = "reboot"
#   nodes                 = ["192.168.122.28", ]
# }

resource "talos_machine_bootstrap" "bootstrap" {
  talos_config = talos_client_configuration.talosconfig.talos_config
  node         = "192.168.122.203"
}

resource "talos_cluster_kubeconfig" "kubeconfig" {
  talos_config = talos_client_configuration.talosconfig.talos_config
  nodes        = ["192.168.122.203"]
}

```

**Comment by NPastorale** [comment]
I'm leaving the rest of the files used so it can be easily reproduced.


outputs.tf
```outputs.tf
output "machineconfig_controlplane" {
  value     = talos_machine_configuration_controlplane.machineconfig_cp.machine_config
  sensitive = true
}

output "machineconfig_worker" {
  value     = talos_machine_configuration_worker.machineconfig_worker.machine_config
  sensitive = true
}

output "talosconfig" {
  value     = talos_client_configuration.talosconfig.talos_config
  sensitive = true
}

# output "talosconfig_dynamic" {
#   value     = data.talos_client_configuration.talosconfig.talos_config
#   sensitive = true
# }

output "kubeconfig" {
  value     = talos_cluster_kubeconfig.kubeconfig.kube_config
  sensitive = true
}

# output "kubeconfig_dynamic" {
#   value     = data.talos_cluster_kubeconfig.kubeconfig.kube_config
#   sensitive = true
# }

```
terraform.tfvars
```terraform.tfvars
cluster_name     = "talostest"
cluster_endpoint = "https://192.168.122.203:6443"
```

variables.tf
```variables.tf
variable "cluster_name" {
  description = "A name to provide for the Talos cluster"
  type        = string
}

variable "cluster_endpoint" {
  description = "The endpoint for the Talos cluster"
  type        = string
}
```

These are pretty close to the examples in the repo

**Comment by frezbo** [comment]
that is indeed surprising, could you check what happens if you explicitly specify node and endpoint in the `talos_machine_configuration_apply`, I'm fairly certain that works. Usually I leave out endpoints and nodes in the `talos_client_configuration` , so might have missed this use case

**Comment by NPastorale** [comment]
That did the trick. It is basically what you said. Removing the `nodes` parameter altogether also resulted in a working cluster.

```main.tf
resource "talos_machine_configuration_apply" "worker_config_apply" {
  talos_config          = talos_client_configuration.talosconfig.talos_config
  machine_configuration = talos_machine_configuration_worker.machineconfig_worker.machine_config
  mode                  = "reboot"
  nodes                 = ["192.168.122.28"]
  endpoints             = ["192.168.122.28"]
}
```

**Comment by frezbo** [comment]
> That did the trick. It is basically what you said. Removing the nodes parameter altogether also resulted in a working cluster.

cool, i think the fix is simple, will test next week a do a new release. Thanks for testing it out.

**Comment by NPastorale** [comment]
Happy to help :smiley:. Thank you for doing the heavy lifting.

**Comment by frezbo** [comment]
okay, this needs some fixing

so the plan is to only support `endpoint` and `node` (singular) for the `talos_machine_configuration_apply` resource, and have a separate `talos_machine_configuration_apply_insecure` resource.

**Comment by NPastorale** [comment]
Any particular reason why only `endpoint` and `node` will be supported? As I would imagine it would be more useful to be able to inform a list, as it is possible now.

On the other hand, it does make sense in scenarios on which you'd like to be able to have particular configurations for each single node, something like hostname comes to mind. But this would also entail having to define separate `talos_machine_configuration_worker` or `talos_machine_configuration_controlplane`. It makes more sense to me to handle such situations programatically instead of utilizing separate `reouserce` objets, as those would scale poorly in comparison.

Lastly, wouldn't something like `talos_machine_configuration_apply_insecure` be better server by an `insecure = true` flag on the already existing `talos_machine_configuration_apply`?

**Comment by frezbo** [comment]
> Any particular reason why only endpoint and node will be supported? As I would imagine it would be more useful to be able to > inform a list, as it is possible now.

The current implementation is broken, it was always tested against a single node always. Also in TF sense since it would retry if it's individual resources it's easier to fail early for a single node if there are some config validation issues. It would be too complex to handle errors from multiple nodes in a retry loop. It would be easier to loop TF for constructs.

> Lastly, wouldn't something like talos_machine_configuration_apply_insecure be better server by an insecure = true flag on the already existing talos_machine_configuration_apply?

Doesn't that mean the user has to change it in code and not actually get easier diff's. I'm not opposed to having `insecure` flag. Just confused if we should expose the user to another option.

WDYT?

**Comment by frezbo** [comment]
> Alternatively, you could always manage everything the insecure way, this is far from ideal though.

the problem of keeping the existing behavior to auto-detect the mode is that if multiple endpoints are specified the client would chose a random one. 

> I'm torn with this one, as you would necessarily have to either create a new resource, i.e the "secure" one

the ux would be something like:

```terraform
talos_machine_configuration_apply_insecure {
  <opts>
}

talos_machine_configuration_apply {
  <opts>
}
```
where both resources are used, the secure one would be a no-op in this case and the `insecure` one would not show a diff on input changes.

**Comment by NPastorale** [comment]
> where both resources are used, the secure one would be a no-op in this case and the `insecure` one would not show a diff on input changes.

Does that mean it would be necessary to eliminate the `insecure` one once the initial setup is done?  Or would it somehow detect when the authentication of the node can be successfully performed and choose that one instead?

**Comment by frezbo** [comment]
> Does that mean it would be necessary to eliminate the insecure one once the initial setup is done? 

it's a  resource that doesn't do anything on updates, so it'll always be a no-op after initial successful creation.

**Comment by NPastorale** [comment]
Gotcha. In that case, it sounds good to me. I'll try it out once it's available.
