### ISSUE TITLE
 Race Condition ?!  (authentication handshake failed: tls: failed to verify certificate: x509 )

### ISSUE THREAD

**Issue by senare** [siderolabs/terraform-provider-talos#184]
I would like some help figuring out what is happening and ofc how to fix it !

I am trying to use the talos-terraform provider and create a cluster inside OpenStack 

So i create network & instances ... followed by configuring DNS and FloatingIP for ctrl plane 

Then I try and create my 'cluster' ...

```
locals {
  cluster_endpoint = format("https://%s.%s:6443", var.cluster_name, var.domain)
}

resource "talos_machine_secrets" "machine_secrets" {}

data "talos_machine_configuration" "machineconfig_cp" {
  cluster_name     = var.cluster_name
  machine_type     = "controlplane"
  cluster_endpoint = local.cluster_endpoint
  machine_secrets  = talos_machine_secrets.machine_secrets.machine_secrets
}

data "talos_machine_configuration" "machineconfig_worker" {
  cluster_name     = var.cluster_name
  machine_type     = "worker"
  cluster_endpoint = local.cluster_endpoint
  machine_secrets  = talos_machine_secrets.machine_secrets.machine_secrets
}

data "talos_client_configuration" "talosconfig" {
  cluster_name    = var.cluster_name
  client_configuration = talos_machine_secrets.machine_secrets.client_configuration
  endpoints       = values(var.controlplanes)
}

resource "local_sensitive_file" "talosconfig" {
  content = data.talos_client_configuration.talosconfig.talos_config
  filename = "/root/.talos/config"
  file_permission = "0755"
}

resource "local_sensitive_file" "machineconfig_worker" {
  content = data.talos_machine_configuration.machineconfig_worker.machine_configuration
  filename = "/root/machineconfig_worker"
  file_permission = "0755"
}

resource "local_sensitive_file" "machineconfig_controlplane" {
  content = data.talos_machine_configuration.machineconfig_cp.machine_configuration
  filename = "/root/machineconfig_controlplane"
  file_permission = "0755"
}

# BOOTSTRAP

resource "talos_machine_configuration_apply" "cp_config_apply" {
  client_configuration        = talos_machine_secrets.machine_secrets.client_configuration
  machine_configuration_input = data.talos_machine_configuration.machineconfig_cp.machine_configuration
  for_each              = var.controlplanes
  endpoint              = each.value
  node                  = each.value
}

resource "talos_machine_configuration_apply" "worker_config_apply" {
  client_configuration        = talos_machine_secrets.machine_secrets.client_configuration
  machine_configuration_input = data.talos_machine_configuration.machineconfig_worker.machine_configuration
  for_each              = var.workers
  endpoint              = each.value
  node                  = each.value
}

locals {
  ip = tolist(values(var.controlplanes))[0]
}

resource "talos_machine_bootstrap" "bootstrap" {
  depends_on = [
    talos_machine_configuration_apply.cp_config_apply
  ]

  client_configuration  = talos_machine_secrets.machine_secrets.client_configuration
  node         = local.ip
}

data "talos_cluster_kubeconfig" "kubeconfig" {
  depends_on = [
    talos_machine_bootstrap.bootstrap
  ]
  client_configuration  = talos_machine_secrets.machine_secrets.client_configuration
  node         = local.ip
}

resource "local_sensitive_file" "kubeconfig" {
  content = data.talos_cluster_kubeconfig.kubeconfig.kubeconfig_raw
  filename = "/root/.kube/config"
  file_permission = "0755"
}
```

unfortunately this eventually fails ...

```
│ Error: Error bootstrapping node
│ 
│   with module.talos_cluster.talos_machine_bootstrap.bootstrap,
│   on ../talos/talos.tf line 67, in resource "talos_machine_bootstrap" "bootstrap":
│   67: resource "talos_machine_bootstrap" "bootstrap" {
│ 
│ rpc error: code = Unavailable desc = connection error: desc = "transport:
│ authentication handshake failed: tls: failed to verify certificate: x509:
│ certificate is valid for 172.16.0.180, not 217.61.247.225"
```

here my cert is valid for internal IP not the external IP (FIP) ...

interesting thing is if I comment out all code below the '# BOOTSTRAP' run that and the add the code back in again and re-run it .. everything works ...

I could really use a few ideas what is happening here ?

**Comment by smira** [comment]
Please make sure you're using the [OpenStack image](https://factory.talos.dev/?arch=amd64&cmdline-set=true&extensions=-&platform=openstack&target=cloud&version=1.7.6) of Talos which _should_ learn your external IP.

If that is already the case, you need to tell Talos about the external IP it doesn't know about by patching the machine configuration with the following [block](https://www.talos.dev/v1.7/reference/configuration/v1alpha1/config/#Config.machine):

```yaml
machine:
  certSANs:
    - 217.61.247.225
```

**Comment by senare** [comment]
Yes I am using the 'https://github.com/siderolabs/talos/releases/download/v1.7.6/openstack-amd64.raw.xz' image

For now I was able to workaround the issues with a sleep (not so pretty .... )

````
resource "talos_machine_configuration_apply" "cp_config_apply" {
  client_configuration        = talos_machine_secrets.machine_secrets.client_configuration
  machine_configuration_input = data.talos_machine_configuration.machineconfig_cp.machine_configuration
  for_each              = var.controlplanes
  node                  = each.value
}

resource "talos_machine_configuration_apply" "worker_config_apply" {
  client_configuration        = talos_machine_secrets.machine_secrets.client_configuration
  machine_configuration_input = data.talos_machine_configuration.machineconfig_worker.machine_configuration
  for_each              = var.workers
  node                  = each.value
}

locals {
  ip = tolist(values(var.controlplanes))[0]
}


resource "time_sleep" "wait_for_it" {
  create_duration = "300s"

  depends_on = [
    talos_machine_configuration_apply.cp_config_apply
  ]
}

resource "talos_machine_bootstrap" "bootstrap" {
  depends_on = [
    time_sleep.wait_for_it,
    talos_machine_configuration_apply.cp_config_apply
  ]

  client_configuration  = talos_machine_secrets.machine_secrets.client_configuration
  node         = local.ip
}

data "talos_cluster_kubeconfig" "kubeconfig" {
  depends_on = [
    talos_machine_bootstrap.bootstrap
  ]
  client_configuration  = talos_machine_secrets.machine_secrets.client_configuration
  node         = local.ip
}
```

My 'certSANs' looks to be empty, i will try and patch with IP and report back if it helps !
```
certSANs: []

```

Sry, unfortunately this might not be so timely on my part as other matter calls ... but I will try ...

**Comment by senare** [comment]
I just wanted to repport back that this seams to do the trick nicely ... dropping the sleep and patch certSANs with FIP (i.e external IP).

```
data "talos_machine_configuration" "machineconfig_cp" {
  cluster_name     = var.cluster_name
  machine_type     = "controlplane"
  cluster_endpoint = local.cluster_endpoint
  machine_secrets  = talos_machine_secrets.machine_secrets.machine_secrets
  config_patches = [
    yamlencode({
      machine = {
        certSANs = tolist(values(var.controlplanes))
      }
    })
  ]
}
``` 
like so or something to make it easy if some one else runs into the same problem

**Comment by senare** [comment]
Sry if I reopen this .. but I thought that I would add some more information here ...

Turns out that this is affecting both the ctrl & worker nodes (same fix applied to the worker nodes makes the problem go away) 

For me this meant that I was getting problems when I applied the Cinder CSI (Openstack storage) chart ... getting errors about unable to connect to socket.

Also I wonder if this something that could/should be improved ? 

Could it be better handled somehow ? 

could one handle the wait/retry inside terraform provider ?

As I understand it 'something' will eventually discover correct external address and this is then down to timing ? 

Could I help in some way ? 

Or is this just me 'holding it wrong', if so could this then be better documented ?

**Comment by smira** [comment]
Let's not mix all issues together, and focus one problem at a time:

* does Talos OpenStack image not discover external IPs? Provide a support bundle, and OpenStack metadata, create an issue with siderolabs/talos
* does Talos discover the external IP, but it comes too late so that Terraform provider fails and doesn't retry? let's open a specific issue with the logs

**Comment by senare** [comment]
> Let's not mix all issues together, and focus one problem at a time:

Yes, I am afraid this is just my lack of understanding and result of 'monkey see monkey do' syndrome  

> * does Talos OpenStack image not discover external IPs? Provide a support bundle, and OpenStack metadata, create an issue with siderolabs/talos

I think it does eventually, I will see if I can find some evidence of either case if so I will try open a more specific ticket for that ! 

> * does Talos discover the external IP, but it comes too late so that Terraform provider fails and doesn't retry? let's open a specific issue with the logs

Yes, I think that is a better description ... 

looking at my problem with ctrl plane ... something fails, retry's and in the end it times out ... saying that cert is for internal-ip not external-ip ... in which case I 'terraform destroy' and re-try again ... I will try and recreate and be more mindful what is going on and try and remember to save some logs ...

looking at my problem with the worker plane ... this is after I think I have a 'working cluster' i.e. kubectl get nodes resturns ctrl & worker nodes which is in ready state ... only when I try and install cinder it fails to talk to ctrl plane, presumably also because there is a bad cert ... (and again to get out of this I  do 'terraform destroy' and re-try again)

So I am guessing that the 'Terraform provider' does retry but that the scope of the operation being retried dont include cert or new Ip or similar ?

In any case again ... I will try and recreate and be more mindful what is going on and try and remember to save some logs ...
