### ISSUE TITLE
More granular talos_cluster_health checks

### ISSUE THREAD

**Issue by rmvangun** [siderolabs/terraform-provider-talos#189]
I've encountered a need to perform some intermediate health checks in order to perform certain bootstrap related activity. In particular, I'd like to install Cilium using first-class Helm via Terraform, vs. using inline manifests in the machine config. The reason is that I would like to continue to manage the lifecycle with helm after initial bootstrap.

The problem with the current health checks is that they fail with these settings until a CNI is bootstrapped:

```
cluster = {
  network = {
    cni = {
      name = "none"
    }
  }
  proxy = {
    disabled = true
  }
}
```

Yet, there is a point at which the API is available, and you can use helm to install Cilium successfully. Then, the health checks succeed.

I've tried using `skip_kubernetes_checks = true` but this can pass before the k8s api endpoint becomes available.

I can likely work around this using a `null_resource`, but it would be nice if there were another flag or a list of checks to perform on the `talos_cluster_health` data source.

**Comment by frezbo** [comment]
Already fixed by #186, we'll cut a new release along with talos 1.8.0-alpha.2
