### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by flokli** [siderolabs/terraform-provider-talos#2]
I found this at https://registry.terraform.io/providers/siderolabs/talos/latest, but it seems right now there's no documentation on how to use it.

Staring at the code, it looks like it defines a `talos_machine_configuration` resource, and requires the following attributes/arguments to be set:

`cluster_name`, `cluster_endpoint`, `common_config_patches`, `control_plane_config_patches`, `worker_config_patches`

… and has the following calculated attributes:

`control_plane_machine_configuration`, `worker_machine_configuration`, `talosconfig`

**Comment by flokli** [comment]
Another interesting thing to document would be on how to import already existing config into a terraform resource.

**Comment by NPastorale** [comment]
It would be very useful to add examples too. A simple configuration for each resource and how to operate with it would go a long way/

**Comment by NPastorale** [comment]
My bad, I didn't see it before posting the comment. Thanks!

**Comment by james-callahan** [comment]
This appears to be basically complete and deficiencies could be created as new issues?
https://registry.terraform.io/providers/siderolabs/talos/latest/docs/

**Comment by frezbo** [comment]
Closing as complete
