### ISSUE TITLE
`talos_machine_bootstrap` rpc error: code = Unimplemented desc = method Bootstrap not implemented

### ISSUE THREAD

**Issue by lmarlow** [siderolabs/terraform-provider-talos#213]
I have been unable to bootstrap new 1.8.3 nodes. `terraform apply` times out with the following error

```shell
talos_machine_bootstrap.talos: Creating...
talos_machine_bootstrap.talos: Still creating... [10s elapsed]

... many minutes later...

╷
│ Error: Error bootstrapping node
│
│   with talos_machine_bootstrap.talos,
│   on talos.tf line 101, in resource "talos_machine_bootstrap" "talos":
│  101: resource "talos_machine_bootstrap" "talos" {
│
│ rpc error: code = Unimplemented desc = method Bootstrap not implemented
╵
```

The console of the controlplane node shows
![image](https://github.com/user-attachments/assets/ea91e7fb-7cbb-49b8-8f51-915acd63e71b)

When I try to use the `data.talos_client_configuration.talos.talos_config` output for this cluster with `talosctl` it fails with a tls error.

```shell
$ terraform output -raw talosconfig > talosconfig

$ talosctl --talosconfig talosconfig bootstrap
error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

```shell
$ terraform version
Terraform v1.9.8
on darwin_amd64
+ provider registry.terraform.io/bpg/proxmox v0.67.1
+ provider registry.terraform.io/siderolabs/talos v0.6.1
```

**Comment by smira** [comment]
the machine configuration hasn't been applied to the machine (or whatever else is the way Talos should acquire machine configuration in your setup).

**Comment by lmarlow** [comment]
@smira, thank you for the response.

I removed the VMs and ran another `apply` from scratch and it looks like the machine configurations are applied. When the controller reboots, it then just keeps responding with `method Bootstrap not implemented`.

After it timed out, I pulled the talonconfig and the controller's machine configuration from `terraform.tfstate` and saved them into local files.

`talosctl --talosconfig talosconfig apply-config --insecure --nodes 192.168.30.201 --file cp.yaml` seemed to run successfully, but I think I just saw an error about `/dev/sda` not existing before it rebooted. I will look more into my Proxmox VM configuration.

**Comment by smira** [comment]
Hard to say without the logs, but it's not the Terraform provider fault strictly - there was something in the install process which failed.

**Comment by lmarlow** [comment]
I will close this for now. It seems I may need to change some VM settings and patches before I get to bootstrapping. Thank you for taking a look.

**Comment by christophe-lucas** [comment]
Had a similar issue last week. The machine config `machine.install.disk` was invalid compared to my VM disk setup.
From [install guide](https://www.talos.dev/v1.8/talos-guides/install/virtualized-platforms/proxmox/#generate-machine-configurations), this cmd should point out available disks:
``` bash
talosctl disks --insecure --nodes $CONTROL_PLANE_IP
```
And then, create your machine config with the correct patch.

Just wondering, is the apply-config resource only design to copy file? Or also wait for the machine to reach the desired state (including potential reboot)?
