### ISSUE TITLE
`talos_machine_configuration_apply`applying configuration to `endpoint` instead of `node` (again)

### ISSUE THREAD

**Issue by rwunderer** [siderolabs/terraform-provider-talos#23]
## Bug Report
This looks very similar to #17 though the resource has been reworked since.

### Description
The following will apply the new configuration to the first **control plane** node instead of **worker 1**:
```
resource "talos_machine_configuration_apply" "worker_config_apply" {
  talos_config          = talos_client_configuration.talosconfig.talos_config
  machine_configuration = talos_machine_configuration_worker.machineconfig_worker.machine_config
  endpoint              = hcloud_server.cp[0].ipv4_address
  node                  = hcloud_server.worker[0].ipv4_address
}
```

The following works as expected:
```
resource "talos_machine_configuration_apply" "worker_config_apply" {
  talos_config          = talos_client_configuration.talosconfig.talos_config
  machine_configuration = talos_machine_configuration_worker.machineconfig_worker.machine_config
  endpoint              = hcloud_server.worker[0].ipv4_address
  node                  = hcloud_server.worker[0].ipv4_address
}
```

### Background
In my clusters I have only the api server on the control plane nodes exposed to my management workstation so I always use the cluster endpoint for talosctl et.al.

Using talosctl this works (10.0.0.6 is the internal ip of the worker node):
```
talosctl -e endpoint.my-cluster.com -n 10.0.0.6 apply-config -f worker.yaml
```

- `endpoint.my-cluster.com` points to the control plane nodes via round-robin dns. If I use that instead of cp[0] in terraform the config gets applied to a random control plane node.
- Using the internal or external ip of the worker node in terraform does not make a difference. Where the config gets applied depends solely on the endpoint selected.

### Environment

- Provider version: `0.1.0-alpha.9`

**Comment by smira** [comment]
@frezbo can you please look into it?

**Comment by rwunderer** [comment]
I cannot reproduce this anymore with the `0.1.0-alpha.10` version of the provider.

(Also part of the problem might have been that the cluster that I was applying to was still on `talos v1.1.x` at the time, not sure)
