### ISSUE TITLE
Take talos_config as structured data rather than a string

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/terraform-provider-talos#36]
It seems odd to have `talos_config` be taken as a string (of yaml encoded data) rather than the actual structure of it.

I end up having to write `jsonencode(local.talosconfig)`; which I'm sure you just de-code on the other end. But this means that you don't get to take advantage of terraform type checking.

Similar issue for e.g. machine configuration.

**Comment by frezbo** [comment]
> It seems odd to have talos_config be taken as a string (of yaml encoded data) rather than the actual structure of it.

this is due to the limitation of the existing terraform provider sdk, the new TF sdk  supports it, but it's not mature enough to switch to it as of now
