### ISSUE TITLE
`endpoint` is a required argument despite it already being in talosconfig

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/terraform-provider-talos#37]
`endpoint` is marked as a required argument despite it already being present inside of the `talos_config`.

**Comment by frezbo** [comment]
correct, this was intentional, as the talos client config is a data source and could have multiple endpoints/nodes defined . but with the resources we'd want it to be explicit which node/endpoint it hits.

**Comment by james-callahan** [comment]
> with the resources we'd want it to be explicit which node/endpoint it hits.

At least so far I don't have any case where I'd need to specify a different endpoint.
IMO it should be an **optional** argument rather than **required**

**Comment by frezbo** [comment]
There's some nuances in how the internal talos client is constructed, and in cases where the node is in maintenance mode the endpoint is a required input, in-order to avoid making more resources to handle secure/insecure mode, it was decided to make endpoint mandatory.

**Comment by james-callahan** [comment]
> in cases where the node is in maintenance mode the endpoint is a required input, in-order to avoid making more resources to handle secure/insecure mode, it was decided to make endpoint mandatory.

I'm confused on how these are related: how does requiring an endpoint make an `insecure` argument/variant not required?

**Comment by frezbo** [comment]
> I'm confused on how these are related: how does requiring an endpoint make an insecure argument/variant not required?

We auto-detect it now, as opposed to explicitly specifying it (which would mean updating the config to be secure once configs are applied, much better UX doing auto detection)
