### ISSUE TITLE
`talos_config` arguments take a whole config rather than a specific context

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/terraform-provider-talos#39]
A talos config can contain several contexts, and may also set a particular context as the default one.

This whole structure doesn't make sense for where a `talos_config` is passed in this provider: it always uses whatever context is set as the default one; which is essentially an un-needed layer of indirection.

Instead of taking a whole talos config, take just the talos context.

**Comment by frezbo** [comment]
this makes sense, the initial implementation was to get a basic working provider. PR's welcome
