### ISSUE TITLE
Failed bootstrap continues trying instead of failing with error

### ISSUE THREAD

**Issue by james-callahan** [siderolabs/terraform-provider-talos#42]
Trying to bootstrap an already bootstrapped cluster (Related: https://github.com/siderolabs/terraform-provider-talos/issues/40) the provider sits there retrying forever. Upon manual cancellation (or timeout eventually I guess?) I get to see an error:

`│ Error: rpc error: code = AlreadyExists desc = etcd data directory is not empty`

**Comment by frezbo** [comment]
This is expected behavior, you cannot bootstrap an already bootstrapped cluster

**Comment by james-callahan** [comment]
> This is expected behavior, you cannot bootstrap an already bootstrapped cluster

It *should* exit with an error when the bootstrap api call fails. Instead it sits there retrying in a loop forever (only showing the error message when the `terraform apply` is interrupted with e.g. Ctrl+C)

**Comment by frezbo** [comment]
PR's welcome, in this case you'd have to match all errors that are not retrayable
