### ISSUE TITLE
Incresing the control plane nodes errors with Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by rgl** [siderolabs/terraform-provider-talos#43]
While playing with this terraform provider at https://github.com/rgl/terraform-libvirt-talos I've successfully started a cluster with a single control plane node and a single work node. But when I try to increase the number of control plane nodes to 3 (by setting the `controller_count` variable), terraform errors out with:

```console
vagrant@dm1:~/Projects/terraform-libvirt-talos$ terraform apply tfplan
talos_client_configuration.talos: Modifying... [id=example]
talos_client_configuration.talos: Modifications complete after 0s [id=example]
libvirt_volume.controller[1]: Creating...
libvirt_volume.controller[2]: Creating...
libvirt_network.talos: Modifying... [id=27999ddc-193a-4308-aa54-58ff67464a75]
libvirt_network.talos: Modifications complete after 0s [id=27999ddc-193a-4308-aa54-58ff67464a75]
libvirt_volume.controller[2]: Creation complete after 0s [id=/var/lib/libvirt/images/terraform_talos_example_c2.img]
libvirt_volume.controller[1]: Creation complete after 0s [id=/var/lib/libvirt/images/terraform_talos_example_c1.img]
libvirt_domain.controller[1]: Creating...
libvirt_domain.controller[2]: Creating...
libvirt_domain.worker[0]: Modifying... [id=a7661ca3-3bf4-4714-b636-4172a4aabb6f]
libvirt_domain.controller[0]: Modifying... [id=9e7197ca-c7e4-4a5b-9cd2-8a73a53dbe47]
libvirt_domain.worker[0]: Modifications complete after 0s [id=a7661ca3-3bf4-4714-b636-4172a4aabb6f]
libvirt_domain.controller[0]: Modifications complete after 0s [id=9e7197ca-c7e4-4a5b-9cd2-8a73a53dbe47]
libvirt_domain.controller[2]: Creation complete after 2s [id=331fcf4d-768b-4f29-9b51-67a91c9ec810]
libvirt_domain.controller[1]: Creation complete after 2s [id=5e03de04-9f5f-4696-8853-df209964071e]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for talos_machine_configuration_apply.controller["c1"] to include new values learned so far during apply, provider
│ "registry.terraform.io/siderolabs/talos" produced an invalid new value for .talos_config: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for talos_machine_configuration_apply.controller["c2"] to include new values learned so far during apply, provider
│ "registry.terraform.io/siderolabs/talos" produced an invalid new value for .talos_config: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

Can you help overcoming this problem?

PS1: If I run terraform plan/apply a second time, it works (after some time, I can see the extra nodes joining the k8s cluster).

PS2: Starting 3 control planes node from the get-go (without an existing cluster) works. It only fails when I try to add more nodes.

**Comment by frezbo** [comment]
i think it's because the endpoints here https://github.com/rgl/terraform-libvirt-talos/blob/main/main.tf#L215 is dynamic and the loop order is not same during every plan (the output of this being referenced in https://github.com/rgl/terraform-libvirt-talos/blob/main/main.tf#L219).

Could you try by creating a dummy talosconfig like this:

```hcl
resource "talos_client_configuration" "talos_dummy" {
  cluster_name    = var.cluster_name
  machine_secrets = talos_machine_secrets.machine_secrets.machine_secrets
}
```

and reference that

**Comment by rgl** [comment]
indeed, using that works, but aren't the endpoints required?

I've also tried to change the resources to use `count` instead of `for_each`, but it also broke with the same error.

**Comment by frezbo** [comment]
> indeed, using that works, but aren't the endpoints required?

the endpoints are not required in the `talos_client_configuration` since `talos_machine_configuration_apply` explicitly requires a node and endpoint be set, which takes precedence over whatever is in the client talosconfig

**Comment by rgl** [comment]
I see. Thanks for clearing that up!

Although, I've still got a nagging feeling that something is off, but I don't quite can get my finger on it. I feel that creating a "dummy" resource is a smoking gun to something that is not quire correct. If this is just me, please feel free to close this issue.

**Comment by frezbo** [comment]
yes, I think there's something off here, but I'm not sure what's the issue too at a quick glance, if anyone's an expert in the TF provider internals having an extra pair of eyes would be useful

**Comment by rsmitty** [comment]
I can at least confirm that I'm seeing the same with our vultr example code when I go from 1->3 CP nodes. Will dive in a bit further in the AM.

**Comment by rsmitty** [comment]
So, doing something like https://github.com/rsmitty/terraform-provider-talos/commit/54de4cd1e81de969dc28dde5544163db3befb185 allows this to work as expected. But it will essentially force a recreate of the talosconfig, but that triggers changes for the existing apply-config resources and stuff as they all depend on the talosconfig. It seems fine, but I'm going to need to dive further to determine if this is acceptable.

**Comment by rgl** [comment]
@rsmitty, did you had a chance to look into this?

**Comment by rsmitty** [comment]
err, I haven't gotten further than what I posted above. but let me revisit over the next day or so. thx for the reminder.

**Comment by rsmitty** [comment]
@rgl, https://github.com/siderolabs/terraform-provider-talos/releases/tag/v0.1.1 should fix this up. shout if you see anything else!

**Comment by rgl** [comment]
thank you! its working :-)
