### ISSUE TITLE
`talos_machine_configuration_apply` not triggered by `talos_machine_configuration_controlplane` update

### ISSUE THREAD

**Issue by benjvfr** [siderolabs/terraform-provider-talos#45]
When the resource `talos_machine_configuration_controlplane` is updated, the resource `talos_machine_configuration_apply` is not triggered for update. Same issue with the `talos_machine_configuration_worker` resource.

Example : 
```
resource "talos_machine_configuration_controlplane" "machineconfig_cp" {
  for_each = {for k, n in var.talos.nodes: k => n if n.type == "control-plane"}

  cluster_name     = var.talos.config.cluster_name
  cluster_endpoint = "https://${local.cp_ip}:6443"
  machine_secrets  = talos_machine_secrets.machine_secrets.machine_secrets

  kubernetes_version = var.talos.config.kubernetes_version
  talos_version      = var.talos.config.talos_version

  config_patches = [
    templatefile("${path.module}/templates/cp.patch.yaml.tpl", {
      hostname      = "${var.talos.config.cluster_name}-${each.value.type}-${random_string.node_id[each.key].result}"
      ip            = each.value.ip
      netmask       = var.network.netmask
      gateway       = var.network.gateway
      mtu           = var.network.mtu
      dns_servers   = var.network.dns_servers
      vip           = var.talos.vip
      talos_version = var.talos.config.talos_version
    })
  ]
}

resource "talos_machine_configuration_apply" "cp_config_apply" {
  for_each = {for k, n in var.talos.nodes: k => n if n.type == "control-plane"}

  talos_config          = talos_client_configuration.talosconfig.talos_config
  machine_configuration = talos_machine_configuration_controlplane.machineconfig_cp[each.key].machine_config
  endpoint              = each.value.ip
  node                  = each.value.ip
}
```

When the config patches of `talos_machine_configuration_controlplane.machineconfig_cp` are updated, the `talos_machine_configuration_apply.cp_config_apply` is not triggered for an update. 

Normally, since the `talos_machine_configuration_controlplane.machineconfig_cp[each.key].machine_config` resource is updated, one should expect that `talos_machine_configuration_apply` is updated, but this is not the case.

The first "terraform apply" generates an update of `talos_machine_configuration_controlplane.machineconfig_cp`, but not of the resource `cp_config_apply`.

If we relaunch the "terraform apply" command, then the `cp_config_apply` resource detects that the `machine_cp.machine_config` resource has been updated... but it takes two "terraform apply" (a first one to update `machineconfig_cp`, and a second one to trigger the `cp_config_apply`). 

Is this normal behavior ?

**Comment by frezbo** [comment]
I saw the same behavior when testing based on the slack thread, this is definitely a bug.
