### ISSUE TITLE
Changes to machineconfig should patch rather than recreate VM

### ISSUE THREAD

**Issue by alubbock** [siderolabs/terraform-provider-talos#58]
When I change machineconfig, it takes two updates (as tracked in #45), but then it changes the VM's `user_data` and tries to recreate the VM. I can use `lifecycle { ignore_changes = [user_data] }` to ignore this and patch by manually retrieving the machine config from the terraform output and applying it using `talosctl`. It'd be great if the provider could handle this itself to do in-place machineconfig updates.

**Comment by smira** [comment]
It's not the behavior of this provider, but rather a VM provider which re-creates the VM on userdata changes.

One way around is to skip userdata in the VM and use maintenance mode + apply config via this provider.
