### ISSUE TITLE
```provider talos``` custom options 

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/terraform-provider-talos#6]
We can set default talos-config in terraform provider section. 
It will use as default value in terraform resources/data sources.

It very useful when you have already prepared cluster and talos-config.
But talos-config has non root (unprivileged) user (RBAC extension is on).

```tf
provider talos {
  talosconfig = "~/.talos/config"
  context = "prepared-cluster"

}
```

* `talosconfig` (String) - path to talos config (talossctl param --talosconfig)
* `context` (String) - context name in talos config (talossctl param --context)

Or

* `ca` (String) - talos certificate (conflict with talosconfig)
* `key` (String) - talos key (conflict with talosconfig)

In both cases:

* `endpoint` (List of String) - talos endpoints

**Comment by smira** [comment]
This doesn't seem to align with the direction of this provider - it manages the secrets for the cluster and generates talosconfig automatically.
