### ISSUE TITLE
only expose raw key material only via one resource/datasource output

### ISSUE THREAD

**Issue by flokli** [siderolabs/terraform-provider-talos#74]
This assumes v0.2.alpha0.

It looks like it's possible to both access the kube-apiserver ca.crt via `talos_machine_secrets.this.machine_secrets["certs"]["k8s"]["cert"]`, as well as `data.talos_cluster_kubeconfig.this.kubernetes_client_configuration.ca_certificate`.

There's also some other (ed25519) cert at `data.talos_cluster_kubeconfig.this.kubernetes_client_configuration.ca_certificate`, which might be the same as `talos_machine_secrets.this.machine_secrets["certs"]["os"]["cert"]`

We should probably only expose these via the `talos_machine_secrets.this.machine_secrets["certs"]` resource, not `data.talos_cluster_kubeconfig` (only a rendered `kubeconfig` there).

In addition, there should probably be some documentation about the different keys present in https://www.talos.dev/v1.3/reference/configuration/ (maybe in https://www.talos.dev/v1.3/advanced/ or https://www.talos.dev/v1.3/learn-more/), that describes the different keys/certs used - ideally using the same names for them consistently.

**Comment by smira** [comment]
`talos_machine_secrets.this.machine_secrets` is a Talos secrets bundle, a source to generate all other outputs, so it's expected that some values match it.
