### ISSUE TITLE
`node` and `endpoint` of data source `talos_cluster_kubeconfig` appear to be backwards

### ISSUE THREAD

**Issue by thebearingedge** [siderolabs/terraform-provider-talos#98]
I am provisioning my control plane nodes to a private network behind a load balancer. Using the load balancer as the endpoint and a node's private ip appears to work everywhere (_e.g._ `talos_machine_bootstrap`, `talosctl`, etc). However, the `talos_cluster_kubeconfig` polls forever until terraform times out with a `dial` error. It seems that the data source was trying to connect to the `node`'s private IP directly and ignoring `endpoint`.

But when I reverse `node` and `endpoint` it works 😅. However, this wouldn't be the first time I misunderstood something about how talos works.

## Not working

```hcl
resource "talos_machine_bootstrap" "main" {
  node                 = var.boot_node
  endpoint             = var.endpoint
  client_configuration = var.client_config
}

data "talos_cluster_kubeconfig" "main" {
  depends_on = [
    talos_machine_bootstrap.main
  ]
  node                 = var.boot_node
  endpoint             = var.endpoint
  client_configuration = var.client_config
}
```

## Working

```hcl
resource "talos_machine_bootstrap" "main" {
  node                 = var.boot_node
  endpoint             = var.endpoint
  client_configuration = var.client_config
}

data "talos_cluster_kubeconfig" "main" {
  depends_on = [
    talos_machine_bootstrap.main
  ]
  node                 = var.endpoint
  endpoint             = var.boot_node
  client_configuration = var.client_config
}
```

## Version

```hcl
version     = "0.3.0"
```

Edit: the talos project is incredible

**Comment by frezbo** [comment]
you'd only need to set the node and ignore the endpoint (it's optional)

**Comment by thebearingedge** [comment]
hi! yes, i do see that endpoint is optional if the node's name is known, but my node 10.64.1.1 is not reachable on the public internet, so I specified `endpoint`. the `client_configuration` does not specify my load balancer's address as far as I can tell, so in that case, it seems `endpoint` is required. it's just surprising that it must be specified in the `node` attribute 🤔

**Comment by frezbo** [comment]
ahh if it's a public ip, the node and endpoint needs to match (otherwise it tries to use the private ip through NAT) :sweat_smile:

**Comment by frezbo** [comment]
This was indeed a bug, thank you noticing (apologies, I assumed this was some other issue), they were passed in backwards, will fix in next release

**Comment by thebearingedge** [comment]
No worries. For what it's worth I tried to find it in the source code but ran out of energy after work 😅.

Thank you so much!
